name: cached_builder
description: Helps to optimize the build_runner by caching generated codes for non changed .dart files
version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: 2.4.0
  crypto: 3.0.2
  hive: 2.2.3
  path: 1.8.3

dev_dependencies:
  lints: 2.0.0
  test: 1.16.0